/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ode_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {9, 1, 1};
static const casadi_int casadi_s3[3] = {17, 1, 1};

/* quadrotor_ode_expl_vde_adj:(i0[13],i1[13],i2[4],i3[9])->(o0[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[0]? arg[0][12] : 0;
  a01=5.0000000000000000e-01;
  a02=arg[1]? arg[1][9] : 0;
  a02=(a01*a02);
  a03=(a00*a02);
  a04=arg[0]? arg[0][11] : 0;
  a05=arg[1]? arg[1][8] : 0;
  a05=(a01*a05);
  a06=(a04*a05);
  a03=(a03+a06);
  a06=arg[0]? arg[0][10] : 0;
  a07=arg[1]? arg[1][7] : 0;
  a07=(a01*a07);
  a08=(a06*a07);
  a03=(a03+a08);
  a08=arg[0]? arg[0][7] : 0;
  a09=2.;
  a10=arg[2]? arg[2][0] : 0;
  a11=4.7052010568605468e-01;
  a12=arg[1]? arg[1][4] : 0;
  a12=(a11*a12);
  a13=(a10*a12);
  a13=(a09*a13);
  a14=(a08*a13);
  a03=(a03-a14);
  a14=arg[0]? arg[0][8] : 0;
  a15=arg[1]? arg[1][3] : 0;
  a15=(a11*a15);
  a16=(a10*a15);
  a16=(a09*a16);
  a17=(a14*a16);
  a03=(a03+a17);
  if (res[0]!=0) res[0][6]=a03;
  a03=(a04*a02);
  a17=(a00*a05);
  a03=(a03-a17);
  a17=arg[1]? arg[1][6] : 0;
  a01=(a01*a17);
  a17=(a06*a01);
  a03=(a03-a17);
  a17=(a08+a08);
  a18=arg[1]? arg[1][5] : 0;
  a11=(a11*a18);
  a10=(a10*a11);
  a10=(a09*a10);
  a17=(a17*a10);
  a03=(a03-a17);
  a17=arg[0]? arg[0][6] : 0;
  a18=(a17*a13);
  a03=(a03-a18);
  a18=arg[0]? arg[0][9] : 0;
  a19=(a18*a16);
  a03=(a03+a19);
  if (res[0]!=0) res[0][7]=a03;
  a03=(a00*a07);
  a19=(a06*a02);
  a03=(a03-a19);
  a19=(a04*a01);
  a03=(a03-a19);
  a19=(a14+a14);
  a19=(a19*a10);
  a03=(a03-a19);
  a19=(a18*a13);
  a03=(a03+a19);
  a19=(a17*a16);
  a03=(a03+a19);
  if (res[0]!=0) res[0][8]=a03;
  a03=(a06*a05);
  a19=(a04*a07);
  a03=(a03-a19);
  a19=(a00*a01);
  a03=(a03-a19);
  a13=(a14*a13);
  a03=(a03+a13);
  a16=(a08*a16);
  a03=(a03+a16);
  if (res[0]!=0) res[0][9]=a03;
  a03=4.4975198614403945e-02;
  a16=(a03*a00);
  a13=3.4620705947577960e+01;
  a19=arg[1]? arg[1][11] : 0;
  a13=(a13*a19);
  a19=(a16*a13);
  a10=2.8884448558448860e-02;
  a20=(a10*a04);
  a21=2.2234476573934145e+01;
  a22=arg[1]? arg[1][12] : 0;
  a21=(a21*a22);
  a22=(a20*a21);
  a19=(a19-a22);
  a22=2.7890469047701413e-02;
  a23=(a04*a21);
  a24=(a00*a13);
  a23=(a23-a24);
  a23=(a22*a23);
  a19=(a19+a23);
  a23=(a14*a02);
  a19=(a19-a23);
  a23=(a18*a05);
  a19=(a19+a23);
  a23=(a17*a07);
  a19=(a19+a23);
  a23=(a08*a01);
  a19=(a19-a23);
  if (res[0]!=0) res[0][10]=a19;
  a22=(a22*a06);
  a19=(a22*a21);
  a23=3.5854542219770046e+01;
  a24=arg[1]? arg[1][10] : 0;
  a23=(a23*a24);
  a00=(a00*a23);
  a24=(a06*a21);
  a00=(a00-a24);
  a10=(a10*a00);
  a19=(a19+a10);
  a16=(a16*a23);
  a19=(a19-a16);
  a16=(a08*a02);
  a19=(a19+a16);
  a16=(a17*a05);
  a19=(a19+a16);
  a16=(a18*a07);
  a19=(a19-a16);
  a16=(a14*a01);
  a19=(a19-a16);
  if (res[0]!=0) res[0][11]=a19;
  a20=(a20*a23);
  a22=(a22*a13);
  a20=(a20-a22);
  a06=(a06*a13);
  a04=(a04*a23);
  a06=(a06-a04);
  a03=(a03*a06);
  a20=(a20+a03);
  a02=(a17*a02);
  a20=(a20+a02);
  a05=(a08*a05);
  a20=(a20-a05);
  a07=(a14*a07);
  a20=(a20+a07);
  a01=(a18*a01);
  a20=(a20-a01);
  if (res[0]!=0) res[0][12]=a20;
  a20=1.;
  a01=casadi_sq(a08);
  a07=casadi_sq(a14);
  a01=(a01+a07);
  a01=(a09*a01);
  a20=(a20-a01);
  a20=(a20*a11);
  a11=(a14*a18);
  a01=(a08*a17);
  a11=(a11-a01);
  a11=(a09*a11);
  a11=(a11*a12);
  a20=(a20+a11);
  a08=(a08*a18);
  a14=(a14*a17);
  a08=(a08+a14);
  a09=(a09*a08);
  a09=(a09*a15);
  a20=(a20+a09);
  if (res[0]!=0) res[0][13]=a20;
  if (res[0]!=0) res[0][14]=a23;
  if (res[0]!=0) res[0][15]=a13;
  if (res[0]!=0) res[0][16]=a21;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ode_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
