/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ode_cost_y_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {9, 1, 1};
static const casadi_int casadi_s4[3] = {24, 1, 1};

/* quadrotor_ode_cost_y_e_fun:(i0[13],i1[0],i2[0],i3[],i4[9])->(o0[24]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  a00=arg[0]? arg[0][1] : 0;
  a01=1.3233000000000000e-01;
  a02=2.;
  a03=arg[0]? arg[0][7] : 0;
  a04=arg[0]? arg[0][8] : 0;
  a05=(a03*a04);
  a06=arg[0]? arg[0][9] : 0;
  a07=arg[0]? arg[0][6] : 0;
  a08=(a06*a07);
  a09=(a05+a08);
  a09=(a02*a09);
  a10=(a01*a09);
  a11=2.6078000000000001e-01;
  a12=(a04*a06);
  a13=(a03*a07);
  a14=(a12-a13);
  a14=(a02*a14);
  a15=(a11*a14);
  a10=(a10+a15);
  a00=(a00+a10);
  a10=arg[4]? arg[4][1] : 0;
  a15=(a00-a10);
  a16=arg[0]? arg[0][0] : 0;
  a17=1.;
  a18=casadi_sq(a04);
  a19=casadi_sq(a06);
  a20=(a18+a19);
  a20=(a02*a20);
  a20=(a17-a20);
  a21=(a01*a20);
  a22=(a03*a06);
  a23=(a04*a07);
  a24=(a22+a23);
  a24=(a02*a24);
  a25=(a11*a24);
  a21=(a21+a25);
  a16=(a16+a21);
  a21=arg[4]? arg[4][0] : 0;
  a25=(a16-a21);
  a15=atan2(a15,a25);
  if (res[0]!=0) res[0][0]=a15;
  a21=(a21-a16);
  a20=(a20*a21);
  a10=(a10-a00);
  a09=(a09*a10);
  a20=(a20+a09);
  a22=(a22-a23);
  a22=(a02*a22);
  a23=arg[4]? arg[4][2] : 0;
  a09=arg[0]? arg[0][2] : 0;
  a01=(a01*a22);
  a00=casadi_sq(a03);
  a18=(a00+a18);
  a18=(a02*a18);
  a18=(a17-a18);
  a11=(a11*a18);
  a01=(a01+a11);
  a09=(a09+a01);
  a23=(a23-a09);
  a22=(a22*a23);
  a20=(a20+a22);
  if (res[0]!=0) res[0][1]=a20;
  a05=(a05-a08);
  a05=(a02*a05);
  a05=(a05*a21);
  a00=(a00+a19);
  a00=(a02*a00);
  a17=(a17-a00);
  a17=(a17*a10);
  a05=(a05+a17);
  a12=(a12+a13);
  a12=(a02*a12);
  a12=(a12*a23);
  a05=(a05+a12);
  if (res[0]!=0) res[0][2]=a05;
  a21=(a24*a21);
  a10=(a14*a10);
  a21=(a21+a10);
  a23=(a18*a23);
  a21=(a21+a23);
  if (res[0]!=0) res[0][3]=a21;
  a21=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][4]=a21;
  a21=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][5]=a21;
  a21=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][6]=a21;
  if (res[0]!=0) res[0][7]=a03;
  if (res[0]!=0) res[0][8]=a04;
  a21=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][9]=a21;
  a23=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][10]=a23;
  a10=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][11]=a10;
  a05=4.7052010568605468e-01;
  a12=2.0842148680769220e+01;
  a24=(a12*a24);
  a13=arg[4]? arg[4][3] : 0;
  a24=(a24+a13);
  a24=(a05*a24);
  if (res[0]!=0) res[0][12]=a24;
  a14=(a12*a14);
  a24=arg[4]? arg[4][4] : 0;
  a14=(a14+a24);
  a14=(a05*a14);
  if (res[0]!=0) res[0][13]=a14;
  a18=(a12*a18);
  a14=arg[4]? arg[4][5] : 0;
  a18=(a18+a14);
  a18=(a05*a18);
  a14=9.8066499999999994e+00;
  a18=(a18-a14);
  if (res[0]!=0) res[0][14]=a18;
  a18=3.5854542219770046e+01;
  a14=arg[4]? arg[4][6] : 0;
  a24=4.4975198614403945e-02;
  a24=(a24*a10);
  a13=(a23*a24);
  a17=2.8884448558448860e-02;
  a17=(a17*a23);
  a00=(a10*a17);
  a13=(a13-a00);
  a14=(a14-a13);
  a18=(a18*a14);
  if (res[0]!=0) res[0][15]=a18;
  a14=3.4620705947577960e+01;
  a13=arg[4]? arg[4][7] : 0;
  a00=2.7890469047701413e-02;
  a00=(a00*a21);
  a19=(a10*a00);
  a24=(a21*a24);
  a19=(a19-a24);
  a13=(a13-a19);
  a14=(a14*a13);
  if (res[0]!=0) res[0][16]=a14;
  a13=2.2234476573934145e+01;
  a19=arg[4]? arg[4][8] : 0;
  a17=(a21*a17);
  a00=(a23*a00);
  a17=(a17-a00);
  a19=(a19-a17);
  a13=(a13*a19);
  if (res[0]!=0) res[0][17]=a13;
  a19=(a02*a06);
  a19=(a12*a19);
  a19=(a05*a19);
  a17=5.0000000000000000e-01;
  a00=(a21*a07);
  a24=(a10*a04);
  a00=(a00+a24);
  a24=(a23*a06);
  a00=(a00-a24);
  a00=(a17*a00);
  a24=(a19*a00);
  a08=(a02*a04);
  a08=(a12*a08);
  a08=(a05*a08);
  a20=(a21*a03);
  a22=(a23*a04);
  a20=(a20+a22);
  a22=(a10*a06);
  a20=(a20+a22);
  a20=(a17*a20);
  a22=(a08*a20);
  a24=(a24-a22);
  a22=(a02*a07);
  a22=(a12*a22);
  a22=(a05*a22);
  a09=(a23*a07);
  a01=(a10*a03);
  a09=(a09-a01);
  a01=(a21*a06);
  a09=(a09+a01);
  a09=(a17*a09);
  a01=(a22*a09);
  a24=(a24+a01);
  a01=(a02*a03);
  a01=(a12*a01);
  a01=(a05*a01);
  a11=(a10*a07);
  a16=(a23*a03);
  a11=(a11+a16);
  a16=(a21*a04);
  a11=(a11-a16);
  a11=(a17*a11);
  a16=(a01*a11);
  a24=(a24+a16);
  if (res[0]!=0) res[0][18]=a24;
  a24=(a01*a20);
  a16=(a22*a00);
  a24=(a24-a16);
  a16=(a19*a09);
  a24=(a24+a16);
  a16=(a08*a11);
  a24=(a24+a16);
  if (res[0]!=0) res[0][19]=a24;
  a24=(a03+a03);
  a24=(a02*a24);
  a24=(a12*a24);
  a24=(a05*a24);
  a16=(a24*a00);
  a15=(a04+a04);
  a15=(a02*a15);
  a15=(a12*a15);
  a15=(a05*a15);
  a25=(a15*a09);
  a16=(a16+a25);
  a16=(-a16);
  if (res[0]!=0) res[0][20]=a16;
  a01=(a17*a01);
  a16=(a23*a01);
  a25=(a05*a11);
  a25=(a12*a25);
  a25=(a02*a25);
  a26=(a16+a25);
  a22=(a17*a22);
  a27=(a10*a22);
  a26=(a26-a27);
  a08=(a17*a08);
  a28=(a21*a08);
  a26=(a26-a28);
  a26=(a26*a00);
  a29=(a10*a01);
  a30=(a23*a22);
  a31=(a29+a30);
  a32=(a05*a09);
  a32=(a12*a32);
  a32=(a02*a32);
  a31=(a31+a32);
  a19=(a17*a19);
  a33=(a21*a19);
  a31=(a31+a33);
  a31=(a31*a20);
  a26=(a26-a31);
  a31=(a10*a19);
  a34=(a21*a01);
  a35=(a23*a08);
  a36=(a34+a35);
  a37=(a05*a20);
  a37=(a12*a37);
  a37=(a02*a37);
  a36=(a36+a37);
  a36=(a31-a36);
  a36=(a36*a09);
  a26=(a26+a36);
  a36=(a21*a22);
  a38=(a10*a08);
  a39=(a36-a38);
  a40=(a23*a19);
  a39=(a39-a40);
  a05=(a05*a00);
  a12=(a12*a05);
  a02=(a02*a12);
  a39=(a39+a02);
  a39=(a39*a11);
  a26=(a26+a39);
  a39=(a06*a22);
  a12=(a04*a01);
  a05=(a39-a12);
  a41=(a03*a08);
  a05=(a05-a41);
  a42=(a07*a19);
  a05=(a05+a42);
  a05=(a05*a18);
  a26=(a26+a05);
  a05=(a03*a01);
  a43=(a07*a22);
  a44=(a05+a43);
  a45=(a04*a08);
  a44=(a44-a45);
  a46=(a06*a19);
  a44=(a44-a46);
  a44=(a44*a14);
  a26=(a26+a44);
  a44=(a07*a01);
  a47=(a03*a22);
  a44=(a44-a47);
  a47=(a06*a08);
  a44=(a44-a47);
  a47=(a04*a19);
  a44=(a44+a47);
  a44=(a44*a13);
  a26=(a26+a44);
  if (res[0]!=0) res[0][21]=a26;
  a37=(a37+a35);
  a37=(a37-a31);
  a37=(a37+a34);
  a37=(a37*a00);
  a38=(a38-a02);
  a38=(a38+a40);
  a38=(a38-a36);
  a38=(a38*a20);
  a37=(a37-a38);
  a25=(a25-a28);
  a25=(a25+a16);
  a25=(a25-a27);
  a25=(a25*a09);
  a37=(a37+a25);
  a33=(a32+a33);
  a33=(a33+a29);
  a33=(a33+a30);
  a33=(a33*a11);
  a37=(a37+a33);
  a46=(a46-a45);
  a46=(a46+a05);
  a46=(a46-a43);
  a46=(a46*a18);
  a37=(a37+a46);
  a41=(a41+a42);
  a41=(a41+a12);
  a41=(a41+a39);
  a41=(a41*a14);
  a37=(a37+a41);
  a08=(a07*a08);
  a19=(a03*a19);
  a08=(a08-a19);
  a01=(a06*a01);
  a08=(a08+a01);
  a22=(a04*a22);
  a08=(a08-a22);
  a08=(a08*a13);
  a37=(a37+a08);
  if (res[0]!=0) res[0][22]=a37;
  a15=(a17*a15);
  a37=(a23*a15);
  a17=(a17*a24);
  a24=(a21*a17);
  a37=(a37+a24);
  a37=(a37*a20);
  a20=(a10*a15);
  a02=(a02+a02);
  a20=(a20-a02);
  a20=(a20*a00);
  a37=(a37+a20);
  a32=(a32+a32);
  a10=(a10*a17);
  a32=(a32+a10);
  a32=(a32*a09);
  a37=(a37-a32);
  a23=(a23*a17);
  a21=(a21*a15);
  a23=(a23-a21);
  a23=(a23*a11);
  a37=(a37+a23);
  a23=(a06*a15);
  a11=(a07*a17);
  a23=(a23+a11);
  a23=(a23*a18);
  a37=(a37-a23);
  a06=(a06*a17);
  a07=(a07*a15);
  a06=(a06-a07);
  a06=(a06*a14);
  a37=(a37+a06);
  a03=(a03*a15);
  a04=(a04*a17);
  a03=(a03-a04);
  a03=(a03*a13);
  a37=(a37+a03);
  if (res[0]!=0) res[0][23]=a37;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_e_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ode_cost_y_e_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_e_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_e_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
