/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ode_cost_y_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {9, 1, 1};
static const casadi_int casadi_s5[3] = {28, 1, 1};

/* quadrotor_ode_cost_y_fun:(i0[13],i1[4],i2[0],i3[],i4[9])->(o0[28]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51;
  a00=arg[0]? arg[0][1] : 0;
  a01=1.3233000000000000e-01;
  a02=2.;
  a03=arg[0]? arg[0][7] : 0;
  a04=arg[0]? arg[0][8] : 0;
  a05=(a03*a04);
  a06=arg[0]? arg[0][9] : 0;
  a07=arg[0]? arg[0][6] : 0;
  a08=(a06*a07);
  a09=(a05+a08);
  a09=(a02*a09);
  a10=(a01*a09);
  a11=2.6078000000000001e-01;
  a12=(a04*a06);
  a13=(a03*a07);
  a14=(a12-a13);
  a14=(a02*a14);
  a15=(a11*a14);
  a10=(a10+a15);
  a00=(a00+a10);
  a10=arg[4]? arg[4][1] : 0;
  a15=(a00-a10);
  a16=arg[0]? arg[0][0] : 0;
  a17=1.;
  a18=casadi_sq(a04);
  a19=casadi_sq(a06);
  a20=(a18+a19);
  a20=(a02*a20);
  a20=(a17-a20);
  a21=(a01*a20);
  a22=(a03*a06);
  a23=(a04*a07);
  a24=(a22+a23);
  a24=(a02*a24);
  a25=(a11*a24);
  a21=(a21+a25);
  a16=(a16+a21);
  a21=arg[4]? arg[4][0] : 0;
  a25=(a16-a21);
  a15=atan2(a15,a25);
  if (res[0]!=0) res[0][0]=a15;
  a21=(a21-a16);
  a20=(a20*a21);
  a10=(a10-a00);
  a09=(a09*a10);
  a20=(a20+a09);
  a22=(a22-a23);
  a22=(a02*a22);
  a23=arg[4]? arg[4][2] : 0;
  a09=arg[0]? arg[0][2] : 0;
  a01=(a01*a22);
  a00=casadi_sq(a03);
  a18=(a00+a18);
  a18=(a02*a18);
  a18=(a17-a18);
  a11=(a11*a18);
  a01=(a01+a11);
  a09=(a09+a01);
  a23=(a23-a09);
  a22=(a22*a23);
  a20=(a20+a22);
  if (res[0]!=0) res[0][1]=a20;
  a05=(a05-a08);
  a05=(a02*a05);
  a05=(a05*a21);
  a00=(a00+a19);
  a00=(a02*a00);
  a17=(a17-a00);
  a17=(a17*a10);
  a05=(a05+a17);
  a12=(a12+a13);
  a12=(a02*a12);
  a12=(a12*a23);
  a05=(a05+a12);
  if (res[0]!=0) res[0][2]=a05;
  a21=(a24*a21);
  a10=(a14*a10);
  a21=(a21+a10);
  a23=(a18*a23);
  a21=(a21+a23);
  if (res[0]!=0) res[0][3]=a21;
  a21=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][4]=a21;
  a21=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][5]=a21;
  a21=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][6]=a21;
  if (res[0]!=0) res[0][7]=a03;
  if (res[0]!=0) res[0][8]=a04;
  a21=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][9]=a21;
  a23=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][10]=a23;
  a10=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][11]=a10;
  a05=4.7052010568605468e-01;
  a12=arg[1]? arg[1][0] : 0;
  a24=(a24*a12);
  a13=arg[4]? arg[4][3] : 0;
  a24=(a24+a13);
  a24=(a05*a24);
  if (res[0]!=0) res[0][12]=a24;
  a14=(a14*a12);
  a24=arg[4]? arg[4][4] : 0;
  a14=(a14+a24);
  a14=(a05*a14);
  if (res[0]!=0) res[0][13]=a14;
  a18=(a18*a12);
  a14=arg[4]? arg[4][5] : 0;
  a18=(a18+a14);
  a18=(a05*a18);
  a14=9.8066499999999994e+00;
  a18=(a18-a14);
  if (res[0]!=0) res[0][14]=a18;
  a18=3.5854542219770046e+01;
  a14=arg[1]? arg[1][1] : 0;
  a24=arg[4]? arg[4][6] : 0;
  a24=(a14+a24);
  a13=4.4975198614403945e-02;
  a13=(a13*a10);
  a17=(a23*a13);
  a00=2.8884448558448860e-02;
  a00=(a00*a23);
  a19=(a10*a00);
  a17=(a17-a19);
  a24=(a24-a17);
  a18=(a18*a24);
  if (res[0]!=0) res[0][15]=a18;
  a24=3.4620705947577960e+01;
  a17=arg[1]? arg[1][2] : 0;
  a19=arg[4]? arg[4][7] : 0;
  a19=(a17+a19);
  a08=2.7890469047701413e-02;
  a08=(a08*a21);
  a20=(a10*a08);
  a13=(a21*a13);
  a20=(a20-a13);
  a19=(a19-a20);
  a24=(a24*a19);
  if (res[0]!=0) res[0][16]=a24;
  a19=2.2234476573934145e+01;
  a20=arg[1]? arg[1][3] : 0;
  a13=arg[4]? arg[4][8] : 0;
  a13=(a20+a13);
  a00=(a21*a00);
  a08=(a23*a08);
  a00=(a00-a08);
  a13=(a13-a00);
  a19=(a19*a13);
  if (res[0]!=0) res[0][17]=a19;
  a13=(a02*a06);
  a13=(a12*a13);
  a13=(a05*a13);
  a00=5.0000000000000000e-01;
  a08=(a21*a07);
  a22=(a10*a04);
  a08=(a08+a22);
  a22=(a23*a06);
  a08=(a08-a22);
  a08=(a00*a08);
  a22=(a13*a08);
  a09=(a02*a04);
  a09=(a12*a09);
  a09=(a05*a09);
  a01=(a21*a03);
  a11=(a23*a04);
  a01=(a01+a11);
  a11=(a10*a06);
  a01=(a01+a11);
  a01=(a00*a01);
  a11=(a09*a01);
  a22=(a22-a11);
  a11=(a02*a07);
  a11=(a12*a11);
  a11=(a05*a11);
  a16=(a23*a07);
  a15=(a10*a03);
  a16=(a16-a15);
  a15=(a21*a06);
  a16=(a16+a15);
  a16=(a00*a16);
  a15=(a11*a16);
  a22=(a22+a15);
  a15=(a02*a03);
  a15=(a12*a15);
  a15=(a05*a15);
  a25=(a10*a07);
  a26=(a23*a03);
  a25=(a25+a26);
  a26=(a21*a04);
  a25=(a25-a26);
  a25=(a00*a25);
  a26=(a15*a25);
  a22=(a22+a26);
  if (res[0]!=0) res[0][18]=a22;
  a22=(a15*a01);
  a26=(a11*a08);
  a22=(a22-a26);
  a26=(a13*a16);
  a22=(a22+a26);
  a26=(a09*a25);
  a22=(a22+a26);
  if (res[0]!=0) res[0][19]=a22;
  a22=(a03+a03);
  a22=(a02*a22);
  a22=(a12*a22);
  a22=(a05*a22);
  a26=(a22*a08);
  a27=(a04+a04);
  a27=(a02*a27);
  a27=(a12*a27);
  a27=(a05*a27);
  a28=(a27*a16);
  a26=(a26+a28);
  a26=(-a26);
  if (res[0]!=0) res[0][20]=a26;
  a15=(a00*a15);
  a26=(a23*a15);
  a28=(a05*a25);
  a28=(a12*a28);
  a28=(a02*a28);
  a29=(a26+a28);
  a11=(a00*a11);
  a30=(a10*a11);
  a29=(a29-a30);
  a09=(a00*a09);
  a31=(a21*a09);
  a29=(a29-a31);
  a29=(a29*a08);
  a32=(a10*a15);
  a33=(a23*a11);
  a34=(a32+a33);
  a35=(a05*a16);
  a35=(a12*a35);
  a35=(a02*a35);
  a34=(a34+a35);
  a13=(a00*a13);
  a36=(a21*a13);
  a34=(a34+a36);
  a34=(a34*a01);
  a29=(a29-a34);
  a34=(a10*a13);
  a37=(a21*a15);
  a38=(a23*a09);
  a39=(a37+a38);
  a40=(a05*a01);
  a40=(a12*a40);
  a40=(a02*a40);
  a39=(a39+a40);
  a39=(a34-a39);
  a39=(a39*a16);
  a29=(a29+a39);
  a39=(a21*a11);
  a41=(a10*a09);
  a42=(a39-a41);
  a43=(a23*a13);
  a42=(a42-a43);
  a05=(a05*a08);
  a05=(a12*a05);
  a02=(a02*a05);
  a42=(a42+a02);
  a42=(a42*a25);
  a29=(a29+a42);
  a42=(a06*a11);
  a05=(a04*a15);
  a44=(a42-a05);
  a45=(a03*a09);
  a44=(a44-a45);
  a46=(a07*a13);
  a44=(a44+a46);
  a44=(a44*a18);
  a29=(a29+a44);
  a44=(a03*a15);
  a47=(a07*a11);
  a48=(a44+a47);
  a49=(a04*a09);
  a48=(a48-a49);
  a50=(a06*a13);
  a48=(a48-a50);
  a48=(a48*a24);
  a29=(a29+a48);
  a48=(a07*a15);
  a51=(a03*a11);
  a48=(a48-a51);
  a51=(a06*a09);
  a48=(a48-a51);
  a51=(a04*a13);
  a48=(a48+a51);
  a48=(a48*a19);
  a29=(a29+a48);
  if (res[0]!=0) res[0][21]=a29;
  a40=(a40+a38);
  a40=(a40-a34);
  a40=(a40+a37);
  a40=(a40*a08);
  a41=(a41-a02);
  a41=(a41+a43);
  a41=(a41-a39);
  a41=(a41*a01);
  a40=(a40-a41);
  a28=(a28-a31);
  a28=(a28+a26);
  a28=(a28-a30);
  a28=(a28*a16);
  a40=(a40+a28);
  a36=(a35+a36);
  a36=(a36+a32);
  a36=(a36+a33);
  a36=(a36*a25);
  a40=(a40+a36);
  a50=(a50-a49);
  a50=(a50+a44);
  a50=(a50-a47);
  a50=(a50*a18);
  a40=(a40+a50);
  a45=(a45+a46);
  a45=(a45+a05);
  a45=(a45+a42);
  a45=(a45*a24);
  a40=(a40+a45);
  a09=(a07*a09);
  a13=(a03*a13);
  a09=(a09-a13);
  a15=(a06*a15);
  a09=(a09+a15);
  a11=(a04*a11);
  a09=(a09-a11);
  a09=(a09*a19);
  a40=(a40+a09);
  if (res[0]!=0) res[0][22]=a40;
  a27=(a00*a27);
  a40=(a23*a27);
  a00=(a00*a22);
  a22=(a21*a00);
  a40=(a40+a22);
  a40=(a40*a01);
  a01=(a10*a27);
  a02=(a02+a02);
  a01=(a01-a02);
  a01=(a01*a08);
  a40=(a40+a01);
  a35=(a35+a35);
  a10=(a10*a00);
  a35=(a35+a10);
  a35=(a35*a16);
  a40=(a40-a35);
  a23=(a23*a00);
  a21=(a21*a27);
  a23=(a23-a21);
  a23=(a23*a25);
  a40=(a40+a23);
  a23=(a06*a27);
  a25=(a07*a00);
  a23=(a23+a25);
  a23=(a23*a18);
  a40=(a40-a23);
  a06=(a06*a00);
  a07=(a07*a27);
  a06=(a06-a07);
  a06=(a06*a24);
  a40=(a40+a06);
  a03=(a03*a27);
  a04=(a04*a00);
  a03=(a03-a04);
  a03=(a03*a19);
  a40=(a40+a03);
  if (res[0]!=0) res[0][23]=a40;
  if (res[0]!=0) res[0][24]=a12;
  if (res[0]!=0) res[0][25]=a14;
  if (res[0]!=0) res[0][26]=a17;
  if (res[0]!=0) res[0][27]=a20;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ode_cost_y_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
