/**:
  ros__parameters:
    mass: 3.4
    ixx: 0.0232
    iyy: 0.0224
    izz: 0.0405
    f_max: 49.05
    w_min: 150.0
    w_max: 1200.0
    arm_l_x: 0.151
    arm_l_y: 0.160
    moment_const: 0.0144
    cam_x: 0.105
    cam_y: 0.0
    cam_z: 0.02
    cam_roll: 0.0
    cam_pitch: 0.0
    cam_yaw: 0.0
    fov_h: 87.0
    fov_v: 58.0
    cf: 1.25e-5
    ct: 1.8e-7
    MPC_controller: 1
    return2autonomous: False
