/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ode_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {9, 1, 1};
static const casadi_int casadi_s4[3] = {5, 1, 1};
static const casadi_int casadi_s5[43] = 
  {17, 5, 0, 7, 14, 21, 28, 35,
  4, 5, 6, 10, 11, 12, 13, 4,
  5, 6, 10, 11, 12, 13, 4, 5,
  6, 10, 11, 12, 13, 4, 5, 6,
  10, 11, 12, 13, 4, 5, 6, 10,
  11, 12, 13};
static const casadi_int casadi_s6[3] = {5, 0, 1};

/* quadrotor_ode_constr_h_fun_jac_uxt_zt:(i0[13],i1[4],i2[0],i3[9])->(o0[5],o1[17x5,35nz],o2[5x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53;
  a00=2.;
  a01=arg[0]? arg[0][7] : 0;
  a02=arg[0]? arg[0][8] : 0;
  a03=(a01*a02);
  a04=arg[0]? arg[0][9] : 0;
  a05=arg[0]? arg[0][6] : 0;
  a06=(a04*a05);
  a07=(a03-a06);
  a07=(a00*a07);
  a08=arg[3]? arg[3][0] : 0;
  a09=arg[0]? arg[0][0] : 0;
  a10=1.3233000000000000e-01;
  a11=1.;
  a12=casadi_sq(a02);
  a13=casadi_sq(a04);
  a14=(a12+a13);
  a14=(a00*a14);
  a14=(a11-a14);
  a15=(a10*a14);
  a16=2.6078000000000001e-01;
  a17=(a01*a04);
  a18=(a02*a05);
  a19=(a17+a18);
  a19=(a00*a19);
  a20=(a16*a19);
  a15=(a15+a20);
  a09=(a09+a15);
  a08=(a08-a09);
  a09=(a07*a08);
  a15=casadi_sq(a01);
  a13=(a15+a13);
  a13=(a00*a13);
  a13=(a11-a13);
  a20=arg[3]? arg[3][1] : 0;
  a21=arg[0]? arg[0][1] : 0;
  a03=(a03+a06);
  a03=(a00*a03);
  a06=(a10*a03);
  a22=(a02*a04);
  a23=(a01*a05);
  a24=(a22-a23);
  a24=(a00*a24);
  a25=(a16*a24);
  a06=(a06+a25);
  a21=(a21+a06);
  a20=(a20-a21);
  a21=(a13*a20);
  a09=(a09+a21);
  a22=(a22+a23);
  a22=(a00*a22);
  a23=arg[3]? arg[3][2] : 0;
  a21=arg[0]? arg[0][2] : 0;
  a17=(a17-a18);
  a17=(a00*a17);
  a18=(a10*a17);
  a15=(a15+a12);
  a15=(a00*a15);
  a11=(a11-a15);
  a15=(a16*a11);
  a18=(a18+a15);
  a21=(a21+a18);
  a23=(a23-a21);
  a21=(a22*a23);
  a09=(a09+a21);
  a21=6.8707767001883757e-01;
  a18=(a14*a08);
  a15=(a03*a20);
  a18=(a18+a15);
  a15=(a17*a23);
  a18=(a18+a15);
  a15=(a21*a18);
  a12=(a09-a15);
  if (res[0]!=0) res[0][0]=a12;
  a09=(a09+a15);
  if (res[0]!=0) res[0][1]=a09;
  a09=(a19*a08);
  a15=(a24*a20);
  a09=(a09+a15);
  a15=(a11*a23);
  a09=(a09+a15);
  a15=3.5219089722442037e-01;
  a12=(a15*a18);
  a06=(a09-a12);
  if (res[0]!=0) res[0][2]=a06;
  a09=(a09+a12);
  if (res[0]!=0) res[0][3]=a09;
  if (res[0]!=0) res[0][4]=a18;
  a18=(a21*a14);
  a09=(a18-a07);
  if (res[1]!=0) res[1][0]=a09;
  a09=(a21*a03);
  a12=(a09-a13);
  if (res[1]!=0) res[1][1]=a12;
  a12=(a21*a17);
  a06=(a12-a22);
  if (res[1]!=0) res[1][2]=a06;
  a06=(a00*a01);
  a25=(a23*a06);
  a26=(a00*a02);
  a27=(a10*a26);
  a28=(a22*a27);
  a28=(a25+a28);
  a29=(a00*a04);
  a30=(a08*a29);
  a31=(a16*a26);
  a32=(a07*a31);
  a32=(a30+a32);
  a33=(a10*a29);
  a34=(a16*a06);
  a35=(a33-a34);
  a36=(a13*a35);
  a32=(a32+a36);
  a28=(a28-a32);
  a32=(a20*a29);
  a36=(a03*a35);
  a36=(a32-a36);
  a37=(a14*a31);
  a36=(a36-a37);
  a37=(a17*a27);
  a38=(a23*a26);
  a37=(a37-a38);
  a36=(a36+a37);
  a37=(a21*a36);
  a39=(a28-a37);
  if (res[1]!=0) res[1][3]=a39;
  a39=(a08*a26);
  a40=(a16*a29);
  a41=(a07*a40);
  a41=(a39-a41);
  a01=(a01+a01);
  a01=(a00*a01);
  a42=(a20*a01);
  a05=(a00*a05);
  a43=(a16*a05);
  a44=(a27-a43);
  a45=(a13*a44);
  a42=(a42+a45);
  a41=(a41-a42);
  a42=(a23*a05);
  a45=(a16*a01);
  a33=(a33-a45);
  a45=(a22*a33);
  a45=(a42-a45);
  a41=(a41+a45);
  a26=(a20*a26);
  a45=(a03*a44);
  a45=(a26-a45);
  a46=(a14*a40);
  a45=(a45-a46);
  a29=(a23*a29);
  a46=(a17*a33);
  a46=(a29-a46);
  a45=(a45+a46);
  a46=(a21*a45);
  a47=(a41-a46);
  if (res[1]!=0) res[1][4]=a47;
  a47=(a08*a06);
  a02=(a02+a02);
  a02=(a00*a02);
  a48=(a10*a02);
  a43=(a43-a48);
  a48=(a07*a43);
  a48=(a47-a48);
  a49=(a10*a06);
  a50=(a49+a40);
  a51=(a13*a50);
  a48=(a48-a51);
  a51=(a10*a05);
  a16=(a16*a02);
  a16=(a51+a16);
  a52=(a22*a16);
  a29=(a29+a52);
  a48=(a48+a29);
  a06=(a20*a06);
  a29=(a03*a50);
  a29=(a06-a29);
  a52=(a08*a02);
  a53=(a14*a43);
  a52=(a52+a53);
  a29=(a29-a52);
  a52=(a17*a16);
  a52=(a52-a42);
  a29=(a29+a52);
  a52=(a21*a29);
  a42=(a48-a52);
  if (res[1]!=0) res[1][5]=a42;
  a42=(a22*a49);
  a38=(a38-a42);
  a42=(a08*a05);
  a04=(a04+a04);
  a00=(a00*a04);
  a10=(a10*a00);
  a34=(a34-a10);
  a10=(a07*a34);
  a10=(a42+a10);
  a04=(a20*a00);
  a51=(a51+a31);
  a53=(a13*a51);
  a04=(a04+a53);
  a10=(a10+a04);
  a38=(a38-a10);
  a20=(a20*a05);
  a05=(a03*a51);
  a05=(a20-a05);
  a08=(a08*a00);
  a00=(a14*a34);
  a08=(a08+a00);
  a05=(a05-a08);
  a08=(a17*a49);
  a25=(a25-a08);
  a05=(a05+a25);
  a21=(a21*a05);
  a25=(a38-a21);
  if (res[1]!=0) res[1][6]=a25;
  a07=(a07+a18);
  a07=(-a07);
  if (res[1]!=0) res[1][7]=a07;
  a13=(a13+a09);
  a13=(-a13);
  if (res[1]!=0) res[1][8]=a13;
  a22=(a22+a12);
  a22=(-a22);
  if (res[1]!=0) res[1][9]=a22;
  a28=(a28+a37);
  if (res[1]!=0) res[1][10]=a28;
  a41=(a41+a46);
  if (res[1]!=0) res[1][11]=a41;
  a48=(a48+a52);
  if (res[1]!=0) res[1][12]=a48;
  a38=(a38+a21);
  if (res[1]!=0) res[1][13]=a38;
  a38=(a15*a14);
  a21=(a38-a19);
  if (res[1]!=0) res[1][14]=a21;
  a21=(a15*a03);
  a48=(a21-a24);
  if (res[1]!=0) res[1][15]=a48;
  a48=(a15*a17);
  a52=(a48-a11);
  if (res[1]!=0) res[1][16]=a52;
  a31=(a19*a31);
  a39=(a39-a31);
  a35=(a24*a35);
  a06=(a06+a35);
  a39=(a39-a06);
  a27=(a11*a27);
  a39=(a39+a27);
  a27=(a15*a36);
  a06=(a39-a27);
  if (res[1]!=0) res[1][17]=a06;
  a40=(a19*a40);
  a30=(a30-a40);
  a44=(a24*a44);
  a20=(a20+a44);
  a30=(a30-a20);
  a01=(a23*a01);
  a33=(a11*a33);
  a01=(a01+a33);
  a30=(a30-a01);
  a01=(a15*a45);
  a33=(a30-a01);
  if (res[1]!=0) res[1][18]=a33;
  a43=(a19*a43);
  a42=(a42-a43);
  a50=(a24*a50);
  a32=(a32-a50);
  a42=(a42+a32);
  a16=(a11*a16);
  a23=(a23*a02);
  a16=(a16-a23);
  a42=(a42+a16);
  a16=(a15*a29);
  a23=(a42-a16);
  if (res[1]!=0) res[1][19]=a23;
  a34=(a19*a34);
  a47=(a47-a34);
  a51=(a24*a51);
  a26=(a26-a51);
  a47=(a47+a26);
  a49=(a11*a49);
  a47=(a47-a49);
  a15=(a15*a05);
  a49=(a47-a15);
  if (res[1]!=0) res[1][20]=a49;
  a19=(a19+a38);
  a19=(-a19);
  if (res[1]!=0) res[1][21]=a19;
  a24=(a24+a21);
  a24=(-a24);
  if (res[1]!=0) res[1][22]=a24;
  a11=(a11+a48);
  a11=(-a11);
  if (res[1]!=0) res[1][23]=a11;
  a39=(a39+a27);
  if (res[1]!=0) res[1][24]=a39;
  a30=(a30+a01);
  if (res[1]!=0) res[1][25]=a30;
  a42=(a42+a16);
  if (res[1]!=0) res[1][26]=a42;
  a47=(a47+a15);
  if (res[1]!=0) res[1][27]=a47;
  a14=(-a14);
  if (res[1]!=0) res[1][28]=a14;
  a03=(-a03);
  if (res[1]!=0) res[1][29]=a03;
  a17=(-a17);
  if (res[1]!=0) res[1][30]=a17;
  if (res[1]!=0) res[1][31]=a36;
  if (res[1]!=0) res[1][32]=a45;
  if (res[1]!=0) res[1][33]=a29;
  if (res[1]!=0) res[1][34]=a05;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ode_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
